# Generated by Django 4.2.3 on 2023-07-14 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
