# Generated by Django 4.2.3 on 2023-08-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0003_task_created_at_task_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
    ]
